Repository wazo-platform/wazo-acceptance, pull requests merged in 2020-12, with the labels that each got.

#113 fix timezone issue on different host
  requirements.txt
  wazo_acceptance/steps/stats.py
Labels: auto-merge, mergeit

#104 Call permission
  features/daily/call_permission.feature
  wazo_acceptance/helpers/__init__.py
  wazo_acceptance/helpers/call_permission.py
  wazo_acceptance/setup.py
  wazo_acceptance/steps/__init__.py
  wazo_acceptance/steps/call_permission.py
  wazo_acceptance/steps/phone_call.py
Labels: mergeit

#112 Wp 169 agent statistic stats
  features/daily/contact-center-stats.feature
  wazo_acceptance/assets/queue-log-clear-one-agent.sh
  wazo_acceptance/steps/agent.py
  wazo_acceptance/steps/phone_call.py
  wazo_acceptance/steps/stats.py
  wazo_acceptance/steps/time.py
Labels: mergeit

#115 increase timeout for queue RINGNOANSWER test
  features/daily/integration-asterisk-queuelog.feature
Labels: auto-merge, mergeit

#114 add a logrotate test for the Asterisk logger
  features/daily/logrotate.feature
  wazo_acceptance/steps/__init__.py
  wazo_acceptance/steps/files.py
  wazo_acceptance/steps/logrotate.py
Labels: mergeit

#117 stats: add fields to fuzzy_statistics
  wazo_acceptance/steps/stats.py
Labels: auto-merge

#116 test qos stats
  features/daily/contact-center-stats.feature
  wazo_acceptance/steps/phone_call.py
  wazo_acceptance/steps/stats.py
Labels: mergeit
