Repository wazo-platform/wazo-acceptance, pull requests merged in 2021-04, with the labels that each got.

#141 add small delay before trying a new transfer
  features/daily/call_transfer.feature
  wazo_acceptance/steps/time.py
Labels: auto-merge, mergeit

#144 do not use deprecated acl_templates term
  wazo_acceptance/prerequisite.py
Labels: auto-merge

#137 remove unused phone call_result logic
  wazo_acceptance/helpers/sip_phone.py
  wazo_acceptance/steps/phone_call.py
Labels: mergeit

#142 Zuul migration
  features/daily/switchboard.feature
  zuul.yaml
Labels: mergeit
